services:
  # No Need to use the umbrel proxy app because gluetun will take over this functionality. Sort of ;-)
  #app_proxy:
  #  environment:
      #PROXY_AUTH_ADD: false
      #APP_HOST: YourID-gluetun_server_1
      #APP_PORT: 8888

  server:
    image: qmcgaw/gluetun:latest
    # container_name: youID-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    #ports:
     # HTTP proxy (not needed when using gluetun as a proxy for other apps)
      # - 8888:8888
      # There is no need to add the portnumbers of the applications that you need to work via gluetun.
      # Gluetun and Umbrel will handle this functionality.
      # Sonarr
      # removed  - 8989:8989
      # Prowlarr
      # removed  - 9696:9696
      # qBittorrent
      # removed  - 8090:8090
      # etc etc etc....
    volumes:
      - ${APP_DATA_DIR}/data:/gluetun
    environment:
      # ProtonVPN VPN Configuration
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTONVPN_PRIVATE_KEY}
      - SERVER_COUNTRIES=France
      # Enable Control server
      - HTTP_CONTROL_SERVER_ADDRESS=8000
      - HTTP_CONTROL_SERVER_LOG=on
      # Enable HTTP proxy
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      # Port forwarding disabled (requires NAT-PMP enabled in Proton WireGuard config)
      - VPN_PORT_FORWARDING=off
      # DNS over TLS
      #- DOT=on
      #- DOT_PROVIDERS=cloudflare,google
      # Ads and malware blocking (not needed if using protonvpn with private key for ade and malware blocking)
      #- BLOCK_ADS=on
      #- BLOCK_MALWARE=on
      # Enable the firewall
      #- FIREWALL=on
      # Enable the kill switch
      #- KILLSWITCH=on 
      # Timezone
      - TZ=Europe/Paris
      # Health checks
      - HEALTH_ENABLED=on
      - HEALTH_TARGET_ADDRESSES=cloudflare.com:443,github.com:443
      - HEALTH_ICMP_TARGET_IPS=1.1.1.1,8.8.8.8
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - HEALTH_RESTART_VPN=on
      # DNS configuration
      - DNS_SERVER=on
      - DNS_UPSTREAM_RESOLVERS=cloudflare
      # Allow local network access
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    restart: unless-stopped
    stop_grace_period: 1m
